forward_client_headers_to_llm_api: true
model_list:
  - model_name: gpt-4o
    litellm_params:
      model: github_copilot/gpt-4o
      extra_headers: {"Editor-Version": "vscode/1.109.5", "Copilot-Integration-Id": "vscode-chat"}
  - model_name: gpt-4o-mini
    litellm_params:
      model: github_copilot/gpt-4o-mini
      extra_headers: {"Editor-Version": "vscode/1.109.5", "Copilot-Integration-Id": "vscode-chat"}
  - model_name: claude-opus
    litellm_params:
      model: github_copilot/claude-opus-4.6
      extra_headers: {"Editor-Version": "vscode/1.109.5", "Copilot-Integration-Id": "vscode-chat"}
  - model_name: claude-sonnet
    litellm_params:
      model: github_copilot/claude-sonnet-4.6
      extra_headers: {"Editor-Version": "vscode/1.109.5", "Copilot-Integration-Id": "vscode-chat"}
  - model_name: claude-haiku
    litellm_params:
      model: github_copilot/claude-haiku-4.5
      extra_headers: {"Editor-Version": "vscode/1.109.5", "Copilot-Integration-Id": "vscode-chat"}
litellm_settings:
  drop_params: true